<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Fun</string>
    <key>scopeName</key>
    <string>source.fun</string>
    <key>fileTypes</key>
    <array>
      <string>fn</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.fun</string>
        <key>match</key>
        <string>//.*$</string>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.declaration.struct.fun</string>
        <key>match</key>
        <string>\b(compound)\s+([A-Za-z_][A-Za-z0-9_]*)(\s*&lt;[^&gt;]+&gt;)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.fun</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.struct.fun</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.parameters.fun</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.declaration.enum.fun</string>
        <key>match</key>
        <string>\b(enum)\s+([A-Za-z_][A-Za-z0-9_]*)(\s*&lt;[^&gt;]+&gt;)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.fun</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.fun</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.parameters.fun</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.declaration.interface.fun</string>
        <key>match</key>
        <string>\b(quirk)\s+([A-Za-z_][A-Za-z0-9_]*)(\s*&lt;[^&gt;]+&gt;)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.fun</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.interface.fun</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.parameters.fun</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.implementation.fun</string>
        <key>match</key>
        <string>\b(impl)\s+([A-Za-z_][A-Za-z0-9_]*)(\s*&lt;[^&gt;]+&gt;)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.fun</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.interface.fun</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.parameters.fun</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>meta.type.generic.fun</string>
        <key>match</key>
        <string>\b([A-Za-z_][A-Za-z0-9_]*)\s*(&lt;[^&gt;]+&gt;)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.fun</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.parameters.fun</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>entity.name.type.fun</string>
        <key>match</key>
        <string>\b([A-Z][A-Za-z0-9_]*)\b(?=\s*(?:\*+)?\s*[A-Za-z_][A-Za-z0-9_]*\b)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.operator.fun</string>
        <key>match</key>
        <string>
          (-&gt;|::|\+=|-=|\*=|/=|%=|==|!=|&lt;=|&gt;=|&amp;&amp;|\|\||&lt;&lt;|&gt;&gt;|\+\+|--|[+\-*/%=&lt;&gt;!&amp;|^~.])</string>
      </dict>
      <dict>
        <key>name</key>
        <string>punctuation.separator.fun</string>
        <key>match</key>
        <string>(;|,|:)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.fun</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.fun</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.single.fun</string>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.fun</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.fun</string>
        <key>match</key>
        <string>
          \b(imp|as|pub|fun|compound|quirk|impl|enum|let|asm|volatile|arch|defer|ret|if|elif|else|for|fit|async|await|break|continue|assert|allow|expect)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>storage.type.fun</string>
        <key>match</key>
        <string>\b(void|raw|num|dec|f32|f64|str|bin|chr|i[1-9][0-9]*|u[1-9][0-9]*)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>support.type.fun</string>
        <key>match</key>
        <string>
          \b(size_t|ptrdiff_t|ssize_t|intptr_t|uintptr_t|int8_t|uint8_t|int16_t|uint16_t|int32_t|uint32_t|int64_t|uint64_t|time_t|clock_t)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.boolean.fun</string>
        <key>match</key>
        <string>\b(true|false)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.fun</string>
        <key>match</key>
        <string>\b\d+(\.\d+)?\b</string>
      </dict>
    </array>
  </dict>
</plist>
