<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Fun</string>
    <key>scopeName</key>
    <string>source.fun</string>
    <key>fileTypes</key>
    <array>
      <string>fn</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.fun</string>
        <key>match</key>
        <string>//.*$</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.double.fun</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.fun</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>string.quoted.single.fun</string>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.fun</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>name</key>
        <string>keyword.control.fun</string>
        <key>match</key>
        <string>
          \b(imp|as|pub|fun|compound|quirk|impl|enum|let|asm|volatile|arch|defer|ret|if|elif|else|for|fit|break|continue|assert)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.fun</string>
        <key>match</key>
        <string>\b(void|raw|num|dec|f32|f64|str|bin|chr|i[1-9][0-9]*|u[1-9][0-9]*|true|false)\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.fun</string>
        <key>match</key>
        <string>\b\d+(\.\d+)?\b</string>
      </dict>
    </array>
  </dict>
</plist>
