name = "Fun"
grammar = "fun"
path_suffixes = ["fn"]
line_comments = ["// "]
block_comment = { start = "/* ", prefix = "* ", end = "*/", tab_size = 1 }
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
tab_size = 2
hard_tabs = false
